# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release

sudo: required

env:
  global:
    - secure: GITHUB_PAT

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
  
script:
  - nohup R --slave --no-restore -e 'shiny::runApp(port = 3000)' &
  
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev